### ISSUE TITLE
关于各个包的版本

### ISSUE THREAD

**Issue by a849173140** [Suphx/Covid19_pyecharts_visualization_local#1]
Hi ，能麻烦告知下需要环境中各个包的版本吗？

**Comment by Suphx** [comment]
用的都是最新的库，其他影响不大，主要是pyecharts 1.0以上的版本，创建图表的语法有所变化。


------------------------------------------------------------------
发件人：a849173140 <notifications@github.com>
发送时间：2020年4月5日(星期日) 14:54
收件人：Suphx/Covid19_pyecharts_visualization_local <Covid19_pyecharts_visualization_local@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[Suphx/Covid19_pyecharts_visualization_local] 关于各个包的版本 (#1)

Hi ，能麻烦告知下需要环境中各个包的版本吗？

**Comment by Suphx** [comment]
用的都是最新的库，其他影响不大，主要是pyecharts 1.0以上的版本，创建图表的语法有所变化。

**Comment by a849173140** [comment]
非常感谢
